require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BancosController do
  before do
    @user = test_sign_in(Factory(:user))
  end
  # This should return the minimal set of attributes required to create a valid
  # Banco. As you add validations to Banco, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:detalle => "detalle1", :user_id => @user.id}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BancosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bancos as @bancos" do
      banco = Banco.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bancos).should eq([banco])
    end
  end

  describe "GET show" do
    it "assigns the requested banco as @banco" do
      banco = Banco.create! valid_attributes
      get :show, {:id => banco.to_param}, valid_session
      assigns(:banco).should eq(banco)
    end
  end

  describe "GET new" do
    it "assigns a new banco as @banco" do
      get :new, {}, valid_session
      assigns(:banco).should be_a_new(Banco)
    end
  end

  describe "GET edit" do
    it "assigns the requested banco as @banco" do
      banco = Banco.create! valid_attributes
      get :edit, {:id => banco.to_param}, valid_session
      assigns(:banco).should eq(banco)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Banco" do
        expect {
          post :create, {:banco => valid_attributes}, valid_session
        }.to change(Banco, :count).by(1)
      end

      it "assigns a newly created banco as @banco" do
        post :create, {:banco => valid_attributes}, valid_session
        assigns(:banco).should be_a(Banco)
        assigns(:banco).should be_persisted
      end

      it "redirects to the created banco" do
        post :create, {:banco => valid_attributes}, valid_session
        response.should redirect_to(Banco.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved banco as @banco" do
        # Trigger the behavior that occurs when invalid params are submitted
        Banco.any_instance.stub(:save).and_return(false)
        post :create, {:banco => {}}, valid_session
        assigns(:banco).should be_a_new(Banco)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Banco.any_instance.stub(:save).and_return(false)
        Banco.any_instance.stub(:errors).and_return('anything')
        post :create, {:banco => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested banco" do
        banco = Banco.create! valid_attributes
        # Assuming there are no other bancos in the database, this
        # specifies that the Banco created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Banco.any_instance.should_receive(:update_attributes).with({'these' => 'params', "user_id"=> @user.id})
        put :update, {:id => banco.to_param, :banco => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested banco as @banco" do
        banco = Banco.create! valid_attributes
        put :update, {:id => banco.to_param, :banco => valid_attributes}, valid_session
        assigns(:banco).should eq(banco)
      end

      it "redirects to the banco" do
        banco = Banco.create! valid_attributes
        put :update, {:id => banco.to_param, :banco => valid_attributes}, valid_session
        response.should redirect_to(banco)
      end
    end

    describe "with invalid params" do
      it "assigns the banco as @banco" do
        banco = Banco.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Banco.any_instance.stub(:save).and_return(false)
        put :update, {:id => banco.to_param, :banco => {}}, valid_session
        assigns(:banco).should eq(banco)
      end

      it "re-renders the 'edit' template" do
        banco = Banco.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Banco.any_instance.stub(:save).and_return(false)
        Banco.any_instance.stub(:errors).and_return('anything')
        put :update, {:id => banco.to_param, :banco => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested banco" do
      banco = Banco.create! valid_attributes
      expect {
        delete :destroy, {:id => banco.to_param}, valid_session
      }.to change(Banco, :count).by(-1)
    end

    it "redirects to the bancos list" do
      banco = Banco.create! valid_attributes
      delete :destroy, {:id => banco.to_param}, valid_session
      response.should redirect_to(bancos_url)
    end
  end

end
