require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MediosDePagoController do

  # This should return the minimal set of attributes required to create a valid
  # MedioDePago. As you add validations to MedioDePago, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all medios_de_pago as @medios_de_pago" do
      medio_de_pago = MedioDePago.create! valid_attributes
      get :index
      assigns(:medios_de_pago).should eq([medio_de_pago])
    end
  end

  describe "GET show" do
    it "assigns the requested medio_de_pago as @medio_de_pago" do
      medio_de_pago = MedioDePago.create! valid_attributes
      get :show, :id => medio_de_pago.id
      assigns(:medio_de_pago).should eq(medio_de_pago)
    end
  end

  describe "GET new" do
    it "assigns a new medio_de_pago as @medio_de_pago" do
      get :new
      assigns(:medio_de_pago).should be_a_new(MedioDePago)
    end
  end

  describe "GET edit" do
    it "assigns the requested medio_de_pago as @medio_de_pago" do
      medio_de_pago = MedioDePago.create! valid_attributes
      get :edit, :id => medio_de_pago.id
      assigns(:medio_de_pago).should eq(medio_de_pago)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MedioDePago" do
        expect {
          post :create, :medio_de_pago => valid_attributes
        }.to change(MedioDePago, :count).by(1)
      end

      it "assigns a newly created medio_de_pago as @medio_de_pago" do
        post :create, :medio_de_pago => valid_attributes
        assigns(:medio_de_pago).should be_a(MedioDePago)
        assigns(:medio_de_pago).should be_persisted
      end

      it "redirects to the created medio_de_pago" do
        post :create, :medio_de_pago => valid_attributes
        response.should redirect_to(MedioDePago.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medio_de_pago as @medio_de_pago" do
        # Trigger the behavior that occurs when invalid params are submitted
        MedioDePago.any_instance.stub(:save).and_return(false)
        post :create, :medio_de_pago => {}
        assigns(:medio_de_pago).should be_a_new(MedioDePago)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MedioDePago.any_instance.stub(:save).and_return(false)
        post :create, :medio_de_pago => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medio_de_pago" do
        medio_de_pago = MedioDePago.create! valid_attributes
        # Assuming there are no other medios_de_pago in the database, this
        # specifies that the MedioDePago created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MedioDePago.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => medio_de_pago.id, :medio_de_pago => {'these' => 'params'}
      end

      it "assigns the requested medio_de_pago as @medio_de_pago" do
        medio_de_pago = MedioDePago.create! valid_attributes
        put :update, :id => medio_de_pago.id, :medio_de_pago => valid_attributes
        assigns(:medio_de_pago).should eq(medio_de_pago)
      end

      it "redirects to the medio_de_pago" do
        medio_de_pago = MedioDePago.create! valid_attributes
        put :update, :id => medio_de_pago.id, :medio_de_pago => valid_attributes
        response.should redirect_to(medio_de_pago)
      end
    end

    describe "with invalid params" do
      it "assigns the medio_de_pago as @medio_de_pago" do
        medio_de_pago = MedioDePago.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MedioDePago.any_instance.stub(:save).and_return(false)
        put :update, :id => medio_de_pago.id, :medio_de_pago => {}
        assigns(:medio_de_pago).should eq(medio_de_pago)
      end

      it "re-renders the 'edit' template" do
        medio_de_pago = MedioDePago.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MedioDePago.any_instance.stub(:save).and_return(false)
        put :update, :id => medio_de_pago.id, :medio_de_pago => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medio_de_pago" do
      medio_de_pago = MedioDePago.create! valid_attributes
      expect {
        delete :destroy, :id => medio_de_pago.id
      }.to change(MedioDePago, :count).by(-1)
    end

    it "redirects to the medios_de_pago list" do
      medio_de_pago = MedioDePago.create! valid_attributes
      delete :destroy, :id => medio_de_pago.id
      response.should redirect_to(medios_de_pago_url)
    end
  end

end
