require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SolicitantesController do

  # This should return the minimal set of attributes required to create a valid
  # Solicitante. As you add validations to Solicitante, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:detalle => "detalle1"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolicitantesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all solicitantes as @solicitantes" do
      solicitante = Solicitante.create! valid_attributes
      get :index, {}, valid_session
      assigns(:solicitantes).should eq([solicitante])
    end
  end

  describe "GET show" do
    it "assigns the requested solicitante as @solicitante" do
      solicitante = Solicitante.create! valid_attributes
      get :show, {:id => solicitante.to_param}, valid_session
      assigns(:solicitante).should eq(solicitante)
    end
  end

  describe "GET new" do
    it "assigns a new solicitante as @solicitante" do
      get :new, {}, valid_session
      assigns(:solicitante).should be_a_new(Solicitante)
    end
  end

  describe "GET edit" do
    it "assigns the requested solicitante as @solicitante" do
      solicitante = Solicitante.create! valid_attributes
      get :edit, {:id => solicitante.to_param}, valid_session
      assigns(:solicitante).should eq(solicitante)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Solicitante" do
        expect {
          post :create, {:solicitante => valid_attributes}, valid_session
        }.to change(Solicitante, :count).by(1)
      end

      it "assigns a newly created solicitante as @solicitante" do
        post :create, {:solicitante => valid_attributes}, valid_session
        assigns(:solicitante).should be_a(Solicitante)
        assigns(:solicitante).should be_persisted
      end

      it "redirects to the created solicitante" do
        post :create, {:solicitante => valid_attributes}, valid_session
        response.should redirect_to(Solicitante.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solicitante as @solicitante" do
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitante.any_instance.stub(:save).and_return(false)
        post :create, {:solicitante => {}}, valid_session
        assigns(:solicitante).should be_a_new(Solicitante)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitante.any_instance.stub(:save).and_return(false)
        Solicitante.any_instance.stub(:errors).and_return('anything')
        post :create, {:solicitante => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested solicitante" do
        solicitante = Solicitante.create! valid_attributes
        # Assuming there are no other solicitantes in the database, this
        # specifies that the Solicitante created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Solicitante.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => solicitante.to_param, :solicitante => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested solicitante as @solicitante" do
        solicitante = Solicitante.create! valid_attributes
        put :update, {:id => solicitante.to_param, :solicitante => valid_attributes}, valid_session
        assigns(:solicitante).should eq(solicitante)
      end

      it "redirects to the solicitante" do
        solicitante = Solicitante.create! valid_attributes
        put :update, {:id => solicitante.to_param, :solicitante => valid_attributes}, valid_session
        response.should redirect_to(solicitante)
      end
    end

    describe "with invalid params" do
      it "assigns the solicitante as @solicitante" do
        solicitante = Solicitante.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitante.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitante.to_param, :solicitante => {}}, valid_session
        assigns(:solicitante).should eq(solicitante)
      end

      it "re-renders the 'edit' template" do
        solicitante = Solicitante.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitante.any_instance.stub(:save).and_return(false)
        Solicitante.any_instance.stub(:errors).and_return('anything')
        put :update, {:id => solicitante.to_param, :solicitante => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solicitante" do
      solicitante = Solicitante.create! valid_attributes
      expect {
        delete :destroy, {:id => solicitante.to_param}, valid_session
      }.to change(Solicitante, :count).by(-1)
    end

    it "redirects to the solicitantes list" do
      solicitante = Solicitante.create! valid_attributes
      delete :destroy, {:id => solicitante.to_param}, valid_session
      response.should redirect_to(solicitantes_url)
    end
  end

end
